pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew build -x test'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        
	stage('Building SONAR') {
		steps {
    			echo 'Using sonarQube to do static code analysis'
    			sh "  ./gradlew sonarqube \
    		        -Dsonar.projectKey=tavisca-merchant \
          		-Dsonar.organization=tavisca-vvinod \
          		-Dsonar.host.url=https://sonarcloud.io \
          		-Dsonar.login=8bb09f07d49f3a4a22373ebd68f5993a1fbc304b"
		}
	}
       stage('Build DockerImage')
        {
            steps {
            sh script: '''
                docker build -t "merchantgalaxy" -f Dockerfile .
                '''
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh "docker login -u varsha3604 -p varshauae123"
                sh "docker tag merchantgalaxy:latest varsha3604/merchantgalaxy:latest"
                sh "docker push varsha3604/merchantgalaxy:latest"
            }
        }
    }
    post{
    	always{
    		deleteDir()
	}
    }
}
