pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew build -x test'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh 'echo "I am in Sonarqube scan"',
            }
        }
       stage('Build DockerImage')
        {
            steps {
            sh "docker build -t "merchantgalaxy" -f Dockerfile . "
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh "docker login -u varsha3604 -p varshauae123"
                sh "docker tag merchantgalaxy:latest varsha3604/merchantgalaxy:latest"
                sh "docker push varsha3604/merchantgalaxy:latest"
            }
        }
    }
    post{
    	always{
    		deleteDir()
	}
    }
}
