pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew build -x test'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        
	stage('Building SONAR') {
		try {
		sh './gradlew clean sonarqube'
		}
		catch (e) {
		emailext attachLog: true, body: 'See attached log', subject: 'BUSINESS Build Failure', to: 'abc@gmail.com'
		step([$class: 'WsCleanup'])
		return
		}
	}
       stage('Build DockerImage')
        {
            steps {
            sh script: '''
                docker build -t "merchantgalaxy" -f Dockerfile .
                '''
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh "docker login -u varsha3604 -p varshauae123"
                sh "docker tag merchantgalaxy:latest varsha3604/merchantgalaxy:latest"
                sh "docker push varsha3604/merchantgalaxy:latest"
            }
        }
    }
    post{
    	always{
    		deleteDir()
	}
    }
}
